import {test,expect} from '@playwright/test';
import {startHarness,adminCredentials} from './harness.mjs';
let harness;
test.beforeAll(async()=>{harness=await startHarness();});
test.afterAll(async()=>{await harness.close();});
async function login(page,email=adminCredentials.email,password=adminCredentials.password){await page.goto(harness.origin+'/login');await page.getByLabel('Business email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();}
async function fillRfq(page,name){await page.getByLabel('Chemical / product',{exact:true}).fill('Acetone');await page.getByLabel('CAS number (if known)',{exact:true}).fill('67-64-1');await page.getByLabel('Required quantity',{exact:true}).fill('5000');await page.getByLabel('Target purity (%)',{exact:true}).fill('99.5');await page.getByLabel('Delivery region',{exact:true}).fill('Chennai, India');await page.getByLabel('Your name',{exact:true}).fill(name);await page.getByLabel('Business email',{exact:true}).fill('public@example.test');await page.getByLabel('Company',{exact:true}).fill('Public Works');await page.getByLabel('Technical & commercial notes',{exact:true}).fill('Five IBC totes, morning delivery.');}
test('public home RFQ/contact submissions appear in real-password admin login, details, counts and status controls',async({page})=>{
 await page.goto(harness.origin+'/');await expect(page.getByRole('link',{name:'Staff portal',exact:true})).toHaveCount(0);await expect(page.locator('a[href="/admin"]')).toHaveCount(0);
 await page.getByRole('link',{name:'Request a custom quote',exact:false}).click();await fillRfq(page,'Guest Procurement');await page.getByRole('button',{name:'Submit quote request',exact:true}).click();await expect(page.getByRole('heading',{name:'Requirement received.'})).toBeVisible();
 const guest=(await harness.store.list('RFQ'))[0];expect(guest.buyer).toBe('');
 await page.goto(harness.origin+'/');await page.getByRole('link',{name:'Contact sales',exact:false}).click();await page.getByLabel('Your name',{exact:true}).fill('Sales Prospect');await page.getByLabel('Business email',{exact:true}).fill('sales@example.test');await page.getByLabel('Company',{exact:true}).fill('Sales Company');await page.getByLabel('How can we help?',{exact:true}).fill('Please contact us about a recurring chemical supply.');await page.getByRole('button',{name:'Send enquiry',exact:true}).click();await expect(page.getByRole('heading',{name:'Enquiry received.'})).toBeVisible();
 await login(page);await expect(page).toHaveURL(/\/admin$/);
 await expect(page.locator('.dashboard-metrics > div').filter({hasText:'New RFQs'}).locator('strong')).toHaveText('1');await expect(page.locator('.dashboard-metrics > div').filter({hasText:'New sales enquiries'}).locator('strong')).toHaveText('1');
 await page.getByRole('button',{name:'Orders',exact:true}).click();await page.getByRole('button',{name:'Quote requests',exact:true}).click();await page.getByRole('link',{name:guest.number,exact:true}).click();
 await expect(page.getByText('Guest Procurement · public@example.test')).toBeVisible();await expect(page.getByText('67-64-1',{exact:true})).toBeVisible();await expect(page.getByText('5,000 L',{exact:true})).toBeVisible();await expect(page.getByText('99.5%',{exact:true})).toBeVisible();await expect(page.getByText('Chennai, India',{exact:true})).toBeVisible();await expect(page.getByText('Five IBC totes, morning delivery.')).toBeVisible();
 await page.getByRole('button',{name:'Mark under review',exact:true}).click();await expect(page.getByRole('button',{name:'Mark under review',exact:true})).toHaveCount(0);
 await page.getByLabel('Total price including freight (USD)',{exact:true}).fill('9500');await page.getByRole('button',{name:'Save commercial quote',exact:true}).click();await expect(page.getByText('$9,500.00',{exact:true})).toBeVisible();
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Decline request',exact:true}).click();await expect(page.getByRole('button',{name:'Save commercial quote',exact:true})).toHaveCount(0);
 await page.goto(harness.origin+'/admin?tab=contacts');await expect(page.getByText('Sales Prospect ·')).toBeVisible();await expect(page.getByRole('link',{name:'sales@example.test'})).toBeVisible();await expect(page.getByText('Please contact us about a recurring chemical supply.')).toBeVisible();
 const select=page.getByRole('combobox',{name:'Status for Sales Company',exact:true});await select.selectOption('contacted');await expect(select).toBeEnabled();await page.reload();await expect(select).toHaveValue('contacted');await select.selectOption('closed');await expect(select).toBeEnabled();await page.reload();await expect(select).toHaveValue('closed');
 await page.getByRole('button',{name:'Overview',exact:true}).click();await expect(page.locator('.dashboard-metrics > div').filter({hasText:'New sales enquiries'}).locator('strong')).toHaveText('0');await expect(page.locator('.dashboard-metrics > div').filter({hasText:'New RFQs'}).locator('strong')).toHaveText('0');
});
test('buyer RFQ attachments reach staff while buyer is blocked from the admin route',async({page})=>{
 await page.goto(harness.origin+'/register?returnTo=/admin');await page.getByLabel('Full name').fill('Buyer Attachments');await page.getByLabel('Company name').fill('Buyer Works');await page.getByLabel('Business email',{exact:true}).fill('attachments@example.test');await page.getByLabel('Password',{exact:true}).fill('Attachment-password-123!');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page).toHaveURL(/\/account$/);
 await page.goto(harness.origin+'/admin');await expect(page.getByRole('heading',{name:'Staff access required.'})).toBeVisible();await expect(page.getByText('Supply, under control.')).toHaveCount(0);
 await page.goto(harness.origin+'/rfq');await fillRfq(page,'Signed-in Procurement');await page.locator('input[type=file]').setInputFiles({name:'technical-specification.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nTest fixture only')});await page.getByRole('button',{name:'Submit quote request',exact:true}).click();await expect(page.getByRole('heading',{name:'Requirement received.'})).toBeVisible();const rfq=(await harness.store.list('RFQ')).find(r=>r.contactName==='Signed-in Procurement');expect(rfq.buyer).toBeTruthy();
 await page.goto(harness.origin+'/account');await page.getByRole('button',{name:'Sign out',exact:true}).click();await login(page);await expect(page).toHaveURL(/\/admin$/);await page.getByRole('button',{name:'Quote requests',exact:true}).click();await page.getByRole('link',{name:rfq.number,exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'technical-specification.pdf',exact:true}).click();expect((await download).suggestedFilename()).toBe('technical-specification.pdf');
});
test('demo login screen keeps Buyer demo but has no Admin demo or public Staff portal',async({page})=>{
 await page.route('**/api/config',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({demo:true})}));await page.goto(harness.origin+'/login');await expect(page.getByRole('button',{name:'Buyer demo',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Admin demo',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Staff portal',exact:true})).toHaveCount(0);
});
