import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {D1Store} from '../shared/store.js';
import {handleApi} from '../shared/api.js';
import {estimate} from '../shared/catalog.js';
import {newSession,digest,hashPassword,now} from '../shared/auth.js';
import {paymentProvider} from '../shared/providers.js';
class TestD1 {
 constructor(){this.sql=new DatabaseSync(':memory:');this.sql.exec(readFileSync(new URL('../drizzle/0000_colossal_miracleman.sql',import.meta.url),'utf8'));}
 prepare(sql){const db=this.sql;return {bind(...args){return {first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args),_sql:sql,_args:args};},_sql:sql,_args:[]};}
 async batch(statements){this.sql.exec('BEGIN');try{const result=statements.map(s=>this.sql.prepare(s._sql).run(...s._args));this.sql.exec('COMMIT');return result;}catch(e){this.sql.exec('ROLLBACK');throw e;}}
}
const db=new TestD1(),store=new D1Store(db,'tests');
const bucketObjects=new Map();const bucket={async put(key,bytes){bucketObjects.set(key,bytes);},async get(key){return bucketObjects.has(key)?{body:bucketObjects.get(key)}:null;}};
const config={demo:true,demoIdentity:'private-test-user',scope:'tests',JWT_SECRET:'test-secret-only-not-for-any-production-environment',FRONTEND_ORIGIN:'https://valence.test',secure:true,crossSite:false,bucket};
async function call(path,{method='GET',body,token,cookie,headers={},cfg=config}={}){const multipart=body instanceof FormData;const req=new Request('https://valence.test/api'+path,{method,headers:{'X-Valence-Client':'web',Origin:'https://valence.test',...(!multipart?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(cookie?{Cookie:cookie}:{}),...headers},...(body?{body:multipart?body:JSON.stringify(body)}:{})});const response=await handleApi(req,store,cfg);const data=response.headers.get('content-type')?.includes('application/json')?await response.json():await response.arrayBuffer();return {status:response.status,data,cookie:response.headers.get('set-cookie')};}
let buyer,admin,newBuyer,address,order,rfq,product;
await test('private demo initializes catalog and buyer; staff sign in with configured password',async()=>{const r=await call('/products');assert.equal(r.status,200);assert.equal(r.data.length,12);product=r.data.find(p=>p.id==='acetone');assert.equal(product.casNumber,'67-64-1');buyer=(await call('/demo/session',{method:'POST',body:{role:'buyer'}})).data;const staff={id:'staff-fixture',name:'Fixture Staff',email:'staff@example.test',passwordHash:await hashPassword('Fixture-staff-password-123!'),role:'admin',companyName:'Fixture',deliveryRegion:'',createdAt:now()};await store.commit([{kind:'User',doc:staff},{kind:'Email',doc:{id:staff.email,buyer:staff.id}}]);admin=(await call('/auth/login',{method:'POST',body:{email:staff.email,password:'Fixture-staff-password-123!'}})).data;assert.equal(buyer.user.role,'buyer');assert.equal(admin.user.role,'admin');address=(await call('/addresses',{token:buyer.accessToken})).data[0];for(const key of ['id','buyer','createdAt'])delete address[key];});
await test('solid packaging is mass-based; server and client estimates agree',async()=>{const p=(await call('/products/citric-acid')).data;assert.ok(p.packagingOptions.every(x=>x.unit==='kg'));const r=await call('/estimate',{method:'POST',body:{productId:'acetone',packagingType:'ibc',quantity:4}});assert.equal(r.status,200);assert.deepEqual(r.data,estimate(product,'ibc',4));assert.equal(r.data.discountPercent,5);});
await test('backend denies unauthenticated and buyer admin access',async()=>{assert.equal((await call('/admin/metrics')).status,401);assert.equal((await call('/admin/metrics',{token:buyer.accessToken})).status,403);assert.equal((await call('/admin/metrics',{token:admin.accessToken})).status,200);});
await test('business registration cannot set admin role or inject query objects',async()=>{const base={name:'Taylor Buyer',email:'taylor@example.com',password:'A-valid-test-password-123!',companyName:'Example Works',deliveryRegion:'Chicago'};assert.equal((await call('/auth/register',{method:'POST',body:{...base,role:'admin'}})).status,400);assert.equal((await call('/auth/login',{method:'POST',body:{email:{$ne:null},password:'whatever'}})).status,400);const r=await call('/auth/register',{method:'POST',body:base});assert.equal(r.status,200);newBuyer=r.data;assert.equal(newBuyer.user.role,'buyer');assert.ok(!JSON.stringify(newBuyer).includes('passwordHash'));assert.match(r.cookie,/HttpOnly/);assert.match(r.cookie,/Secure/);assert.match(r.cookie,/SameSite=Lax/);assert.equal((await call('/auth/register',{method:'POST',body:base})).status,409);});
await test('buyer record ownership prevents IDOR',async()=>{assert.equal((await call('/orders/demo-delivered',{token:newBuyer.accessToken})).status,404);assert.equal((await call('/rfqs/demo-quote',{token:newBuyer.accessToken})).status,404);});
await test('CSRF and origin validation protect cookie endpoints',async()=>{assert.equal((await call('/auth/refresh',{method:'POST',headers:{Origin:'https://attacker.example'}})).status,403);assert.equal((await call('/auth/logout',{method:'POST',headers:{'X-Valence-Client':''}})).status,403);});
await test('cart persists and rejects invalid quantities and price tampering',async()=>{const line={productId:'acetone',packagingType:'drum',quantity:2};assert.equal((await call('/cart/items',{method:'POST',token:buyer.accessToken,body:{...line,quantity:-1}})).status,400);assert.equal((await call('/cart/items',{method:'POST',token:buyer.accessToken,body:{...line,priceCents:1}})).status,400);const r=await call('/cart/items',{method:'POST',token:buyer.accessToken,body:line});assert.equal(r.status,200);assert.equal(r.data.lines[0].quantity,2);assert.equal((await new D1Store(db,'tests').get('Cart','demo-buyer')).lines[0].quantity,2);});
await test('checkout reserves stock atomically, snapshots price, and is idempotent',async()=>{const body={shippingAddress:address,idempotencyKey:'checkout-1'};const r=await call('/checkout',{method:'POST',token:buyer.accessToken,body});assert.equal(r.status,200,JSON.stringify(r.data));order=r.data.order;assert.equal(order.totalCents,105500);assert.equal(order.paymentStatus,'unpaid');assert.equal((await store.get('Product','acetone')).packagingOptions[0].stockUnits,22);assert.equal((await store.get('Cart','demo-buyer')).lines.length,0);const again=await call('/checkout',{method:'POST',token:buyer.accessToken,body});assert.equal(again.data.order.id,order.id);assert.equal((await store.get('Product','acetone')).packagingOptions[0].stockUnits,22);});
await test('staff cannot fulfill unpaid orders; demo payment is explicit and idempotent',async()=>{assert.equal((await call('/admin/orders/'+order.id,{method:'PATCH',token:admin.accessToken,body:{orderStatus:'processing',trackingNumber:'',fulfillmentNotes:''}})).status,409);let r=await call('/orders/'+order.id+'/demo-pay',{method:'POST',token:buyer.accessToken});assert.equal(r.status,200);assert.equal(r.data.paymentStatus,'demo-paid');r=await call('/orders/'+order.id+'/demo-pay',{method:'POST',token:buyer.accessToken});assert.equal(r.data.history.filter(h=>h.status==='paid').length,1);assert.equal((await call('/admin/orders/'+order.id,{method:'PATCH',token:admin.accessToken,body:{orderStatus:'delivered',trackingNumber:'',fulfillmentNotes:''}})).status,409);for(const status of ['processing','shipped','delivered'])assert.equal((await call('/admin/orders/'+order.id,{method:'PATCH',token:admin.accessToken,body:{orderStatus:status,trackingNumber:'TEST-TRACKING',fulfillmentNotes:'Test fulfillment'}})).status,200);});
await test('unpaid cancellation restores inventory exactly once',async()=>{await call('/cart/items',{method:'POST',token:buyer.accessToken,body:{productId:'acetone',packagingType:'drum',quantity:1}});const r=await call('/checkout',{method:'POST',token:buyer.accessToken,body:{shippingAddress:address,idempotencyKey:'cancel-me'}});const id=r.data.order.id;assert.equal((await store.get('Product','acetone')).packagingOptions[0].stockUnits,21);for(let i=0;i<2;i++)assert.equal((await call('/orders/'+id+'/cancel',{method:'POST',token:buyer.accessToken})).status,200);assert.equal((await store.get('Product','acetone')).packagingOptions[0].stockUnits,22);});
await test('RFQ submission → review → quote → accepted order is durable and idempotent',async()=>{let r=await call('/rfqs',{method:'POST',token:buyer.accessToken,body:{productName:'Acetone',casNumber:'67-64-1',amount:5000,unit:'L',targetPurity:99.5,deliveryRegion:'Chicago',notes:'Five IBCs',contactName:'Alex Morgan',contactEmail:'buyer@valence.example',companyName:'Northstar Manufacturing',attachmentIds:[]}});assert.equal(r.status,201);rfq=r.data;r=await call('/admin/rfqs/'+rfq.id+'/status',{method:'POST',token:admin.accessToken,body:{status:'under-review'}});assert.equal(r.status,200);r=await call('/admin/rfqs/'+rfq.id+'/quote',{method:'POST',token:admin.accessToken,body:{priceCents:950000,leadTimeDays:7,notes:'Freight included.'}});assert.equal(r.status,200);assert.equal((await call('/rfqs/'+rfq.id+'/respond',{method:'POST',token:newBuyer.accessToken,body:{decision:'accepted',shippingAddress:address}})).status,404);const payload={decision:'accepted',shippingAddress:address};r=await call('/rfqs/'+rfq.id+'/respond',{method:'POST',token:buyer.accessToken,body:payload});assert.equal(r.status,200,JSON.stringify(r.data));const again=await call('/rfqs/'+rfq.id+'/respond',{method:'POST',token:buyer.accessToken,body:payload});assert.equal(again.data.order.id,r.data.order.id);assert.equal(r.data.order.totalCents,950000);assert.equal((await store.get('RFQ',rfq.id)).status,'converted');});
await test('upload byte/type validation and private attachment authorization',async()=>{const body=new FormData();body.append('kind','attachment');body.append('file',new File(['fake content'],'invalid.pdf',{type:'application/pdf'}));assert.equal((await call('/uploads',{method:'POST',token:buyer.accessToken,body})).status,400);const valid=new FormData();valid.append('kind','attachment');valid.append('file',new File(['%PDF-1.4\nTest fixture only'],'fixture.pdf',{type:'application/pdf'}));const r=await call('/uploads',{method:'POST',token:buyer.accessToken,body:valid});assert.equal(r.status,201);assert.equal((await call('/files/'+r.data.id,{token:buyer.accessToken})).status,200);assert.equal((await call('/files/'+r.data.id,{token:newBuyer.accessToken})).status,404);assert.equal((await call('/files/'+r.data.id)).status,404);});
await test('atomic compare-and-swap rolls back every write after a stale version',async()=>{const old=await store.get('Product','acetone');await store.commit([{kind:'Product',doc:{...old,description:'Updated once'}}]);const before=(await store.get('Product','acetone')).packagingOptions[0].stockUnits;await assert.rejects(store.commit([{kind:'Meta',doc:{id:'must-rollback'}},{kind:'Product',doc:{...old,description:'Stale'}}]));assert.equal(await store.get('Meta','must-rollback'),null);assert.equal((await store.get('Product','acetone')).packagingOptions[0].stockUnits,before);});
await test('production mode disables demo auth/payment and requires approved documentation',async()=>{const cfg={...config,demo:false,demoIdentity:null,STRIPE_SECRET_KEY:'sk_test_fixture'};assert.equal((await call('/demo/session',{method:'POST',body:{role:'admin'},cfg})).status,404);assert.equal((await call('/orders/'+order.id+'/demo-pay',{method:'POST',token:buyer.accessToken,cfg})).status,404);await call('/cart/items',{method:'POST',token:buyer.accessToken,body:{productId:'acetone',packagingType:'drum',quantity:1}});const r=await call('/checkout',{method:'POST',token:buyer.accessToken,body:{shippingAddress:address,idempotencyKey:'prod-denied'},cfg});assert.equal(r.status,400);assert.match(r.data.message,/documentation/);});
await test('Stripe webhook requires signature, amount and reference; duplicate paid event is harmless',async()=>{const cfg={...config,demo:false,STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture'};const doc={...order,id:'stripe-order',_v:undefined,paymentProvider:'stripe',paymentReference:'cs_fixture',paymentStatus:'unpaid',orderStatus:'pending',history:[{status:'pending',at:new Date().toISOString()}]};await store.commit([{kind:'Order',doc}]);const event={id:'evt_fixture',type:'checkout.session.completed',data:{object:{id:'cs_fixture',metadata:{orderId:doc.id,scope:'tests'},payment_status:'paid',currency:'usd',amount_total:doc.totalCents}}};const raw=JSON.stringify(event),t=Math.floor(Date.now()/1000),k=await crypto.subtle.importKey('raw',new TextEncoder().encode(cfg.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=Buffer.from(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(t+'.'+raw))).toString('hex');assert.equal((await call('/webhooks/stripe',{method:'POST',body:event,cfg})).status,400);for(let i=0;i<2;i++)assert.equal((await call('/webhooks/stripe',{method:'POST',body:event,headers:{'stripe-signature':`t=${t},v1=${signature}`},cfg})).status,200);assert.equal((await store.get('Order',doc.id)).paymentStatus,'paid');assert.equal((await store.get('Order',doc.id)).history.length,2);});
await test('refresh rotation detects replay and revokes the session',async()=>{const r=await call('/auth/login',{method:'POST',body:{email:'taylor@example.com',password:'A-valid-test-password-123!'}});assert.equal(r.status,200);const oldCookie=r.cookie.split(';')[0];const rotated=await call('/auth/refresh',{method:'POST',cookie:oldCookie});assert.equal(rotated.status,200);assert.notEqual(rotated.cookie,r.cookie);assert.equal((await call('/auth/refresh',{method:'POST',cookie:oldCookie})).status,401);assert.equal((await call('/me',{token:rotated.data.accessToken})).status,401);});
await test('single-use password reset updates hash and revokes existing sessions',async()=>{const forgot=await call('/auth/forgot-password',{method:'POST',body:{email:'taylor@example.com'}});assert.equal(forgot.status,200);const token=new URL(forgot.data.demoResetUrl).searchParams.get('token'),password='My-new-test-password-456!';assert.equal((await call('/auth/reset-password',{method:'POST',body:{token,password}})).status,200);assert.equal((await call('/auth/reset-password',{method:'POST',body:{token,password}})).status,400);assert.equal((await call('/auth/login',{method:'POST',body:{email:'taylor@example.com',password}})).status,200);const ref=await store.get('Email','taylor@example.com'),u=await store.get('User',ref.buyer);assert.match(u.passwordHash,/^\$2[ab]\$12\$/);assert.ok(await store.get('Reset',await digest(token)));});
await test('health endpoint confirms database readiness',async()=>{const r=await call('/health');assert.equal(r.status,200);assert.equal(r.data.ok,true);});
