import {useState} from 'react';
import {Link,useSearchParams,useNavigate} from 'react-router-dom';
import {Package,FileText,Building2,MapPin,LogOut,ArrowUpRight,Plus,Trash2,Pencil} from 'lucide-react';
import {useApp} from '../lib/context';
import {api} from '../lib/api';
import {PageHeading,useLoad,ErrorBox,Loading,Empty,Badge,money,date,Field,AddressFields} from '../components/UI';
import {blankAddress} from './Checkout';
export default function Account(){const {user,logout,toast}=useApp(),[params,setParams]=useSearchParams(),tab=params.get('tab')||'orders',navigate=useNavigate();const tabs=[['orders','Orders',Package],['rfqs','Quote requests',FileText],['profile','Company profile',Building2],['addresses','Delivery addresses',MapPin]];return <section className="section catalog"><div className="container"><PageHeading eyebrow="BUYER ACCOUNT" title={'Hello, '+user.name.split(' ')[0]+'.'} action={<button className="btn btn-ghost" onClick={async()=>{try{await logout();navigate('/');}catch(e){toast(e.message,'error');}}}><LogOut size={16}/> Sign out</button>}>{user.companyName} · {user.email}</PageHeading><nav className="tabs" aria-label="Account sections">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setParams({tab:id})}><Icon size={17}/>{label}</button>)}</nav>{tab==='orders'?<History kind="orders"/>:tab==='rfqs'?<History kind="rfqs"/>:tab==='profile'?<Profile/>:<Addresses/>}</div></section>;}
export function History({kind,provided}){const result=useLoad(provided?null:'/'+kind),data=provided||result.data;return <><ErrorBox error={result.error} retry={result.reload}/>{!data&&!result.error?<Loading/>:data?.length===0?<Empty title={kind==='orders'?'No orders yet.':'No quote requests yet.'} to={kind==='orders'?'/products':'/rfq'} label={kind==='orders'?'Browse catalog':'Request a quote'}>Your {kind==='orders'?'purchase history':'technical requirements and commercial responses'} will appear here.</Empty>:data&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>{kind==='orders'?'Supply':'Requirement'}</th><th>Date</th><th>Status</th><th>{kind==='orders'?'Total':'Quoted price'}</th><th/></tr></thead><tbody>{data.filter(Boolean).map(x=><tr key={x.id}><td><Link className="mono inline-link" to={'/'+kind+'/'+x.id}>{x.number}</Link></td><td>{kind==='orders'?(x.lines||[]).map(l=>l?.name||'Unspecified item').join(', ')||'—':x.productName}{kind==='rfqs'&&<span className="table-secondary">{(Number.isFinite(x.amount)?x.amount.toLocaleString():'—')} {x.unit}</span>}</td><td>{date(x.createdAt)}</td><td><Badge value={kind==='orders'?x.orderStatus:x.status}/></td><td>{kind==='orders'?money(x.totalCents):x.quote?money(x.quote.priceCents):'Awaiting quote'}</td><td><Link className="icon-button" aria-label={'View '+x.number} to={'/'+kind+'/'+x.id}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>}</>;}
function Profile(){const {user,setUser,toast}=useApp(),[data,setData]=useState({name:user.name,companyName:user.companyName,deliveryRegion:user.deliveryRegion||''}),[busy,setBusy]=useState(false),[error,setError]=useState(null);return <form className="form-card profile-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);try{setUser(await api('/me',{method:'PATCH',body:data}));toast('Company profile updated.');}catch(e){setError(e);}finally{setBusy(false);}}}><h2>Company profile</h2><ErrorBox error={error}/>{[['name','Your name'],['companyName','Company name'],['deliveryRegion','Delivery region']].map(([key,label])=><Field key={key} label={label} value={data[key]} required={key!=='deliveryRegion'} maxLength={key==='name'?100:150} onChange={e=>setData({...data,[key]:e.target.value})}/>)}<Field label="Business email" value={user.email} disabled hint="The sign-in email is fixed for this account."/><button className="btn btn-teal" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>;}
function Addresses(){const {data,error,reload}=useLoad('/addresses'),{user,toast}=useApp(),[editing,setEditing]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[problem,setProblem]=useState(null);async function save(e){e.preventDefault();setBusy(true);setProblem(null);try{await api('/addresses'+(editing?'/'+editing:''),{method:editing?'PATCH':'POST',body:form});setForm(null);setEditing(null);reload();toast('Delivery address saved.');}catch(e){setProblem(e);}finally{setBusy(false);}}return <><div className="section-toolbar"><h2>Saved delivery addresses</h2><button className="btn btn-sm" onClick={()=>{setEditing(null);setForm({...blankAddress,name:user.name,companyName:user.companyName});}}><Plus size={16}/> Add address</button></div><ErrorBox error={error||problem} retry={reload}/>{form&&<form className="form-card profile-card" onSubmit={save}><h2>{editing?'Edit address':'New delivery address'}</h2><AddressFields value={form} onChange={setForm}/><div className="actions"><button className="btn btn-teal" disabled={busy}>Save address</button><button className="btn btn-ghost" type="button" onClick={()=>setForm(null)}>Cancel</button></div></form>}<div className="address-grid">{data?.map(a=><article className="form-card" key={a.id}><h3>{a.label}</h3><strong>{a.name}</strong><p>{a.companyName}<br/>{a.line1}<br/>{a.line2&&<>{a.line2}<br/></>}{a.city}, {a.state} {a.postalCode}<br/>{a.country}</p><span className="mono">{a.phone}</span><div className="actions"><button className="text-button" onClick={()=>{const {id,buyer,createdAt,...rest}=a;setEditing(id);setForm(rest);}}><Pencil size={15}/> Edit</button><button className="text-button danger" onClick={async()=>{if(!window.confirm('Remove this delivery address?'))return;try{await api('/addresses/'+a.id,{method:'DELETE'});reload();}catch(e){setProblem(e);}}}><Trash2 size={15}/> Remove</button></div></article>)}</div>{data?.length===0&&!form&&<Empty title="No saved addresses."/>}</>;}
