import {useState} from 'react';
import {Link,Navigate,useNavigate,useSearchParams,useLocation} from 'react-router-dom';
import {ArrowRight,ShieldCheck,UserRound,Settings2} from 'lucide-react';
import {useApp} from '../lib/context';
import {api} from '../lib/api';
import {Field,ErrorBox,Loading} from '../components/UI';
export function RequireAuth({admin=false,children}){const {user,ready,sessionError,retrySession}=useApp(),location=useLocation();if(!ready)return <Loading/>;if(sessionError)return <section className="section container"><ErrorBox error={sessionError} retry={retrySession}/></section>;if(!user)return <Navigate replace to={'/login?returnTo='+encodeURIComponent(location.pathname+location.search)}/>;if(admin&&user.role!=='admin')return <section className="section"><div className="container narrow"><h1>Staff access required.</h1><p>Your buyer account does not have access to operations.</p><Link className="btn" to="/account">Return to your account</Link><Link className="btn btn-ghost" to="/login?returnTo=/admin">Switch account</Link></div></section>;return children;}
export function safeReturnTo(raw){return typeof raw==='string'&&raw.startsWith('/')&&!raw.startsWith('//')&&!/[\\\x00-\x1f]/.test(raw)&&!/^\/admin(?:[/?#]|$)/.test(raw)?raw:'/account';}
export default function Auth({mode='login'}){
 const {signin,config,toast}=useApp(),navigate=useNavigate(),[params]=useSearchParams(),[busy,setBusy]=useState(false),[error,setError]=useState(null),[message,setMessage]=useState(''),[resetUrl,setResetUrl]=useState('');const signup=mode==='register',forgot=mode==='forgot',reset=mode==='reset';const [data,setData]=useState({name:'',email:'',password:'',companyName:'',deliveryRegion:''});
 const raw=params.get('returnTo')||'/account',returnTo=safeReturnTo(raw);
 const field=(key,label,props={})=><Field label={label} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})} required {...props}/>;
 async function submit(e){e.preventDefault();setBusy(true);setError(null);try{if(forgot){const r=await api('/auth/forgot-password',{method:'POST',body:{email:data.email}});setMessage(r.message);setResetUrl(r.demoResetUrl||'');}else if(reset){if(!params.get('token'))throw new Error('This reset link is missing its token. Request a new password reset.');const r=await api('/auth/reset-password',{method:'POST',body:{token:params.get('token')||'',password:data.password}});toast(r.message);navigate('/login');}else{const signedIn=await signin('/auth/'+(signup?'register':'login'),signup?data:{email:data.email,password:data.password});navigate(signedIn.role==='admin'?'/admin':returnTo);}}catch(err){setError(err);}finally{setBusy(false);}}
 async function demo(){setBusy(true);setError(null);try{await signin('/demo/session',{role:'buyer'});navigate(returnTo);}catch(e){setError(e);}finally{setBusy(false);}}
 return <section className="auth-page section"><div className="container auth-grid"><div className="auth-copy"><span className="eyebrow">VALENCE BUYER PORTAL</span><h1>Your supply chain.<br/>A clearer view.</h1><p>Orders, technical requirements and commercial responses, connected to your company account.</p><div className="auth-benefits"><p><ShieldCheck size={20}/> Secure company account</p><p><UserRound size={20}/> Saved delivery profiles</p><p><Settings2 size={20}/> Orders and quotes in one place</p></div></div><div className="form-card auth-card"><h2>{signup?'Create your buyer account':forgot?'Reset your password':reset?'Choose a new password':'Welcome back.'}</h2><p className="muted">{signup?'Register with your business email.':forgot?'We’ll create a secure reset request.':reset?'Use at least 12 characters.':'Sign in to continue your procurement.'}</p><ErrorBox error={error}/>{message&&<div className="info-box">{message}{!config?.emailConfigured&&<p>Email delivery has not been connected yet.</p>}{resetUrl&&<Link className="inline-link" to={new URL(resetUrl).pathname+new URL(resetUrl).search}>Open demo reset link →</Link>}</div>}<form onSubmit={submit}>{signup&&<>{field('name','Full name',{autoComplete:'name',maxLength:100})}{field('companyName','Company name',{autoComplete:'organization',maxLength:150})}{field('deliveryRegion','Delivery region',{required:false,maxLength:150})}</>}{!reset&&field('email','Business email',{type:'email',autoComplete:'email',maxLength:254})}{!forgot&&field('password',reset?'New password':'Password',{type:'password',minLength:signup||reset?12:1,maxLength:72,autoComplete:signup||reset?'new-password':'current-password',hint:signup?'At least 12 characters.':null})}{!signup&&!forgot&&!reset&&<Link className="forgot-link" to="/forgot-password">Forgot password?</Link>}<button type="submit" className="btn btn-teal full" disabled={busy}>{busy?'Please wait…':signup?'Create account':forgot?'Request reset':reset?'Update password':'Sign in'}<ArrowRight size={17}/></button></form><p className="auth-switch">{signup?'Already have an account?':'New to Valence?'} <Link to={(signup?'/login':'/register')+'?returnTo='+encodeURIComponent(returnTo)}>{signup?'Sign in':'Create an account'}</Link></p>{config?.demo&&!forgot&&!reset&&<div className="demo-access"><span className="eyebrow">EXPLORE THE WORKING DEMO</span><p>Explore the buyer procurement workflow.</p><div className="field-pair"><button className="btn btn-ghost" disabled={busy} onClick={demo}>Buyer demo</button></div><small>Isolated demo accounts. No real payments or shipments.</small></div>}</div></div></section>;
}
