import {useEffect,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,LockKeyhole} from 'lucide-react';
import {useApp} from '../lib/context';
import {api} from '../lib/api';
import {AddressFields,ErrorBox,Loading,PageHeading,Empty} from '../components/UI';
import {OrderSummary} from './Cart';
export const blankAddress={label:'Main facility',name:'',companyName:'',line1:'',line2:'',city:'',state:'',postalCode:'',country:'',phone:''};
export default function Checkout(){const {user,cart,config,reloadCart}=useApp(),navigate=useNavigate(),[params]=useSearchParams(),orderId=params.get('order'),[order,setOrder]=useState(null),[addresses,setAddresses]=useState([]),[address,setAddress]=useState({...blankAddress,name:user.name,companyName:user.companyName}),[error,setError]=useState(null),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false),[key]=useState(()=>crypto.randomUUID());useEffect(()=>{api('/addresses').then(a=>{setAddresses(a);if(a[0]){const {id,buyer,createdAt,...rest}=a[0];setAddress(rest);}}).catch(setError);if(orderId)api('/orders/'+orderId).then(o=>{setOrder(o);if(o.shippingAddress){const {id,buyer,createdAt,...rest}=o.shippingAddress;setAddress(rest);}}).catch(setError);},[orderId]);async function submit(e){e.preventDefault();setBusy(true);setError(null);try{const result=await api('/checkout',{method:'POST',body:{shippingAddress:address,idempotencyKey:key,...(orderId?{orderId}:{})}});await reloadCart();if(result.checkoutUrl)window.location.assign(result.checkoutUrl);else navigate('/orders/'+result.order.id);}catch(e){setError(e);}finally{setBusy(false);}}const data=orderId?order:cart;return <section className="section catalog"><div className="container"><PageHeading eyebrow="SECURE CHECKOUT" title="Confirm your delivery.">Your final price is calculated and checked by the server before payment.</PageHeading><ErrorBox error={error}/>{!data?<Loading/>:!orderId&&!data.lines.length?<Empty title="Your cart is empty." to="/products"/>:<form className="checkout-layout" onSubmit={submit}><div className="form-card"><h2>Delivery address</h2>{addresses.length>0&&<label className="field"><span>Use a saved address</span><select defaultValue="" onChange={e=>{const a=addresses.find(x=>x.id===e.target.value);if(a){const {id,buyer,createdAt,...rest}=a;setAddress(rest);}}}><option value="">Select a saved address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.label} · {a.city}</option>)}</select></label>}<AddressFields value={address} onChange={setAddress}/><label className="checkbox-field"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I have reviewed the specifications and <Link to="/terms" target="_blank">terms of sale</Link>, and I am authorized to procure on behalf of my company.</span></label></div><OrderSummary data={data}>{config?.demo&&<div className="info-box">Demo checkout. No card details or real payment are collected. You can simulate payment on the next screen.</div>}<button className="btn btn-teal full" disabled={busy||!accepted} type="submit">{busy?'Preparing order…':config?.demo?'Create demo order':'Continue to Stripe'}<ArrowRight size={17}/></button><p className="secure-caption"><LockKeyhole size={15}/>{config?.demo?'Isolated demonstration order':'Payment confirmed by Stripe webhook'}</p></OrderSummary></form>}</div></section>;}
