import {useEffect,useState} from 'react';
import {NavLink,Link,useLocation} from 'react-router-dom';
import {ShoppingCart,UserRound,Sun,Moon,Menu,X,ArrowUpRight} from 'lucide-react';
import {useApp} from '../lib/context';
export default function Header(){
 const {user,cart,config}=useApp(),[open,setOpen]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('valence-theme')==='dark');const location=useLocation();
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('valence-theme',dark?'dark':'light');},[dark]);useEffect(()=>setOpen(false),[location.pathname]);
 const count=cart?.lines?.reduce((s,l)=>s+l.quantity,0)||0;
 return <><div className="utility-bar"><div className="container"><span>INDUSTRIAL CHEMISTRY. COMMERCIAL CLARITY.</span><span>{config?.demo?'DEMO ENVIRONMENT · NO REAL PAYMENTS':'TECHNICAL PROCUREMENT PORTAL'}<Link to="/contact">Contact sales <ArrowUpRight size={13}/></Link></span></div></div><header className="site-header"><div className="container header-inner"><NavLink className="brand" to="/" aria-label="Valence home"><span className="brand-mark">V<span>·</span></span><span>VALENCE<small>CHEMICAL GROUP</small></span></NavLink><nav className={open?'is-open':''} aria-label="Main navigation"><NavLink to="/products">Products</NavLink><NavLink to="/capabilities">Capabilities</NavLink><NavLink to="/quality">Quality</NavLink><NavLink to="/volume-calculator">Bulk calculator</NavLink></nav><div className="header-actions"><button className="icon-button theme-toggle" onClick={()=>setDark(!dark)} aria-label={dark?'Switch to light mode':'Switch to dark mode'}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><NavLink className="icon-button" to="/account" aria-label="Buyer account"><UserRound size={20}/></NavLink><NavLink className="icon-button cart-icon" to="/cart" aria-label={'Cart, '+count+' units'}><ShoppingCart size={20}/>{count>0&&<span>{count}</span>}</NavLink><Link className="btn btn-sm header-quote" to="/rfq">Request quote <ArrowUpRight size={15}/></Link><button className="icon-button menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></div>{user?.role==='admin'&&<div className="admin-strip"><div className="container">Signed in as {user.name}<Link to="/admin">Open operations dashboard <ArrowUpRight size={14}/></Link></div></div>}</header></>;
}
